stages:
  - build

variables:
  IMG_NAME: "${CI_REGISTRY_IMAGE}/portainer-bot"

build-docker-images:
  image: docker:20.10.10
  stage: build
  tags:
    - build
  only:
    - tags
    - main
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - VERSION=$(git describe | sed "s/^v//")
    - docker build -t $IMG_NAME:$VERSION .
    - docker tag $IMG_NAME:$VERSION $IMG_NAME:latest
    - docker push $IMG_NAME:$VERSION
    - docker push $IMG_NAME:latest
